#### Cleaning and treating VCS data

In [1]:
import pandas as pd
import re
from datetime import datetime

#### Retirements

In [2]:
retired_df = pd.read_excel('vcus_retired.xlsx')
retired_df.head()

c:\Users\Victor\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Issuance Date,Sustainable Development Goals,Vintage Start,Vintage End,ID,Name,Country/Area,Project Type,Methodology,Total Vintage Quantity,Quantity Issued,Serial Number,Additional Certifications,Retirement/Cancellation Date,Retirement Beneficiary,Retirement Reason,Retirement Details
0,2024-03-25,06: Clean Water and Sanitation; 13: Climate Ac...,2020-01-01,2020-12-31,607,Darkwoods Forest Carbon Project,Canada,Agriculture Forestry and Other Land Use,VM0012,277899,2000,16522-767002131-767004130-VCS-VCU-261-VER-CA-1...,06: Clean Water and Sanitation; 13: Climate Ac...,2024-04-03,NaN,NaN,NaN
1,2024-03-19,NaN,2018-01-01,2018-12-31,868,REDD project in Brazil nut concessions in Madr...,Peru,Agriculture Forestry and Other Land Use,VM0007,2317178,1100,16506-764164779-764165878-VCS-VCU-263-VER-PE-1...,NaN,2024-03-20,Compensación del e-commerce de Cencosud Retail...,Retirement for Person or Organization,NaN
2,2024-03-12,NaN,2019-01-01,2019-12-31,960,Lumin/Eucapine Uruguay Forest Plantations on d...,Uruguay,Agriculture Forestry and Other Land Use,AR-ACM0001,624642,1200,16464-763313284-763314483-VCS-VCU-263-VER-UY-1...,CCB-No Distinction,2024-03-14,NaN,NaN,NaN
3,2024-03-12,NaN,2017-01-01,2017-12-31,2317,REDD+ Project Magnolios de Yarumal,Colombia,Agriculture Forestry and Other Land Use,VM0015,2759,341,16468-763334131-763334471-VCS-VCU-1323-VER-CO-...,NaN,2024-03-19,Betsson Group 2024,Environmental Benefit,Betsson Group 2024
4,2024-03-12,NaN,2016-02-23,2016-12-31,2317,REDD+ Project Magnolios de Yarumal,Colombia,Agriculture Forestry and Other Land Use,VM0015,2468,1926,16469-763334472-763336397-VCS-VCU-1323-VER-CO-...,NaN,2024-03-19,Betsson Group 2024,Environmental Benefit,Betsson Group 2024

In [3]:
retired_columns = retired_df.columns.tolist()

retired_columns

['Issuance Date',
 'Sustainable Development Goals',
 'Vintage Start',
 'Vintage End',
 'ID',
 'Name',
 'Country/Area',
 'Project Type',
 'Methodology',
 'Total Vintage Quantity',
 'Quantity Issued',
 'Serial Number',
 'Additional Certifications',
 'Retirement/Cancellation Date',
 'Retirement Beneficiary',
 'Retirement Reason',
 'Retirement Details']

In [4]:
dropped_columns = [
    'Issuance Date',
    'Sustainable Development Goals',
    'Vintage Start',
    'Methodology',
    'Total Vintage Quantity',
    'Serial Number',
    'Additional Certifications',
    'Retirement Reason',
    'Retirement Details'
]

In [5]:
retired_df.drop(columns=dropped_columns, inplace=True)

retired_df

,Vintage End,ID,Name,Country/Area,Project Type,Quantity Issued,Retirement/Cancellation Date,Retirement Beneficiary
0,2020-12-31,607,Darkwoods Forest Carbon Project,Canada,Agriculture Forestry and Other Land Use,2000,2024-04-03,NaN
1,2018-12-31,868,REDD project in Brazil nut concessions in Madr...,Peru,Agriculture Forestry and Other Land Use,1100,2024-03-20,Compensación del e-commerce de Cencosud Retail...
2,2019-12-31,960,Lumin/Eucapine Uruguay Forest Plantations on d...,Uruguay,Agriculture Forestry and Other Land Use,1200,2024-03-14,NaN
3,2017-12-31,2317,REDD+ Project Magnolios de Yarumal,Colombia,Agriculture Forestry and Other Land Use,341,2024-03-19,Betsson Group 2024
4,2016-12-31,2317,REDD+ Project Magnolios de Yarumal,Colombia,Agriculture Forestry and Other Land Use,1926,2024-03-19,Betsson Group 2024
...,...,...,...,...,...,...,...,...
213101,2007-10-20,1,7.25 MW wind energy project of Aruppukottai Sr...,India,Energy industries (renewable/non-renewable sou...,34,2017-02-08,NaN
213102,2006-12-31,2,LITL's Wind Power Project at Tamilnadu,India,Energy industries (renewable/non-renewable sou...,1260,2009-12-03,NaN
213103,2007-12-31,2,LITL's Wind Power Project at Tamilnadu,India,Energy industries (renewable/non-renewable sou...,12015,2009-12-03,NaN
213104,2007-12-31,2,LITL's Wind Power Project at Tamilnadu,India,Energy industries (renewable/non-renewable sou...,725,2009-12-03,NaN
213105,2007-12-31,2,LITL's Wind Power Project at Tamilnadu,India,Energy industries (renewable/non-renewable sou...,3360,2010-11-17,NaN

In [6]:
retired_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213106 entries, 0 to 213105
Data columns (total 8 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Vintage End                   213106 non-null  datetime64[ns]
 1   ID                            213106 non-null  int64
 2   Name                          213106 non-null  object
 3   Country/Area                  213106 non-null  object
 4   Project Type                  213106 non-null  object
 5   Quantity Issued               213106 non-null  int64
 6   Retirement/Cancellation Date  213106 non-null  datetime64[ns]
 7   Retirement Beneficiary        97600 non-null   object
dtypes: datetime64[ns](2), int64(2), object(4)
memory usage: 13.0+ MB

In [7]:
def replace_chars_in_column(df, column_name, replacement_char=' '):
    non_normal_pattern = re.compile('[^\x00-\x7F]')  # Matches any character outside the ASCII range (non-ASCII characters)
    
    # Apply the function to the specified column in the DataFrame
    retired_df['Retirement Beneficiary'] = retired_df['Retirement Beneficiary'].apply(lambda x: non_normal_pattern.sub(replacement_char, str(x)))
    
    return df


retired_df = replace_chars_in_column(retired_df, retired_df['Retirement Beneficiary'])

In [8]:
retired_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213106 entries, 0 to 213105
Data columns (total 8 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Vintage End                   213106 non-null  datetime64[ns]
 1   ID                            213106 non-null  int64
 2   Name                          213106 non-null  object
 3   Country/Area                  213106 non-null  object
 4   Project Type                  213106 non-null  object
 5   Quantity Issued               213106 non-null  int64
 6   Retirement/Cancellation Date  213106 non-null  datetime64[ns]
 7   Retirement Beneficiary        213106 non-null  object
dtypes: datetime64[ns](2), int64(2), object(4)
memory usage: 13.0+ MB

In [9]:
retired_df.to_csv(r'C:\Users\Victor\Documents\Programming\Portfolio\Power BI\DB\retired_df.csv', index=False, encoding='utf-8')

#### Active

In [10]:
active_df = pd.read_excel('vcus_active.xlsx')

active_df.head()

c:\Users\Victor\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Issuance Date,Sustainable Development Goals,Vintage Start,Vintage End,ID,Name,Country/Area,Project Type,Methodology,Total Vintage Quantity,Quantity Issued,Serial Number,Additional Certifications,Retirement/Cancellation Date,Retirement Beneficiary,Retirement Reason,Retirement Details
0,2024-04-03,NaN,2017-01-01,2017-12-31,868,REDD project in Brazil nut concessions in Madr...,Peru,Agriculture Forestry and Other Land Use,VM0007,2366747,252,16564-773386523-773386774-VCS-VCU-263-VER-PE-1...,NaN,NaT,NaN,NaN,NaN
1,2024-04-03,NaN,2018-01-01,2018-12-31,883,Madushan Hydropower Project on Honghe River in...,China,Energy industries (renewable/non-renewable sou...,ACM0002,1120868,67000,16556-773253916-773320915-VCS-VCU-262-VER-CN-1...,NaN,NaT,NaN,NaN,NaN
2,2024-04-03,NaN,2020-01-01,2020-12-31,928,Yunnan Mangli Hydropower Project,China,Energy industries (renewable/non-renewable sou...,ACM0002,39181,39181,16557-773320916-773360096-VCS-VCU-259-VER-CN-1...,NaN,NaT,NaN,NaN,NaN
3,2024-04-03,NaN,2021-01-01,2021-07-31,928,Yunnan Mangli Hydropower Project,China,Energy industries (renewable/non-renewable sou...,ACM0002,13422,13422,16558-773360097-773373518-VCS-VCU-259-VER-CN-1...,NaN,NaT,NaN,NaN,NaN
4,2024-04-03,NaN,2012-10-02,2012-12-31,500,Positive Climate Care 3.55 MW bundled Grid con...,India,Energy industries (renewable/non-renewable sou...,AMS-I.D.,387,387,16559-773373519-773373905-VCS-VCU-337-VER-IN-1...,NaN,NaT,NaN,NaN,NaN

In [11]:
active_df.columns.tolist()

['Issuance Date',
 'Sustainable Development Goals',
 'Vintage Start',
 'Vintage End',
 'ID',
 'Name',
 'Country/Area',
 'Project Type',
 'Methodology',
 'Total Vintage Quantity',
 'Quantity Issued',
 'Serial Number',
 'Additional Certifications',
 'Retirement/Cancellation Date',
 'Retirement Beneficiary',
 'Retirement Reason',
 'Retirement Details']

In [12]:
dropped_columns_act = [
    'Issuance Date',
    'Sustainable Development Goals',
    'Vintage Start',
    'Methodology',
    'Total Vintage Quantity',
    'Serial Number',
    'Retirement/Cancellation Date',
    'Retirement Beneficiary',
    'Retirement Reason',
    'Retirement Details'
]

active_df.drop(columns=dropped_columns_act, inplace=True)

active_df.head()

,Vintage End,ID,Name,Country/Area,Project Type,Quantity Issued,Additional Certifications
0,2017-12-31,868,REDD project in Brazil nut concessions in Madr...,Peru,Agriculture Forestry and Other Land Use,252,NaN
1,2018-12-31,883,Madushan Hydropower Project on Honghe River in...,China,Energy industries (renewable/non-renewable sou...,67000,NaN
2,2020-12-31,928,Yunnan Mangli Hydropower Project,China,Energy industries (renewable/non-renewable sou...,39181,NaN
3,2021-07-31,928,Yunnan Mangli Hydropower Project,China,Energy industries (renewable/non-renewable sou...,13422,NaN
4,2012-12-31,500,Positive Climate Care 3.55 MW bundled Grid con...,India,Energy industries (renewable/non-renewable sou...,387,NaN

In [13]:
active_df.to_csv(r'C:\Users\Victor\Documents\Programming\Portfolio\Power BI\DB\active_df.csv', index=False, encoding='utf-8')

#### Registered Projects

In [14]:
registered_projects = pd.read_excel('registered.xlsx')

registered_projects.head()

c:\Users\Victor\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,ID,Name,Proponent,Project Type,AFOLU Activities,Methodology,Status,Country/Area,Estimated Annual Emission Reductions,Region,Project Registration Date,Crediting Period Start Date,Crediting Period End Date
0,4443,Jinan Pingyin Youran Dairy Cattle Manure Manag...,"Jinan Youran Animal Husbandry Co., Ltd.","Livestock, enteric fermentation, and manure ma...",NaN,AMS-III.D.,Registered,China,35133,Asia,2024-03-14,2021-09-05,2028-09-04
1,4423,NEW HOPE AWMS GHG Mitigation Project In Anhui ...,Multiple Proponents,"Livestock, enteric fermentation, and manure ma...",NaN,ACM0010,Registered,China,126761,Asia,2024-01-21,2021-08-01,2028-07-31
2,4412,Xiding AWMS GHG Mitigation Project,"Xiding Technology Group Co., Ltd.","Livestock, enteric fermentation, and manure ma...",NaN,AMS-III.D.; AMS-III.F.,Registered,China,82738,Asia,2024-03-14,2021-08-19,2031-08-18
3,4376,Haishang Biogas Recovery and Utilization Project,Shaoyang County Haishang Ecological Agricultur...,"Livestock, enteric fermentation, and manure ma...",NaN,AMS-III.D.,Registered,China,58300,Asia,2023-11-19,2022-01-01,2031-12-31
4,4349,Yueyang LFG Power Generation Project,"Yueyang Weiteng New Energy Co., Ltd.",Energy industries (renewable/non-renewable sou...,NaN,AMS-I.D.; AMS-III.G.,Registered,China,28517,Asia,2024-02-16,2021-11-26,2031-11-25

In [15]:
registered_projects.columns.tolist()

['ID',
 'Name',
 'Proponent',
 'Project Type',
 'AFOLU Activities',
 'Methodology',
 'Status',
 'Country/Area',
 'Estimated Annual Emission Reductions',
 'Region',
 'Project Registration Date',
 'Crediting Period Start Date',
 'Crediting Period End Date']

In [16]:
drop_columns_reg = [
    'AFOLU Activities',
    'Methodology',
    'Status',
    'Estimated Annual Emission Reductions',
    'Region',
    'Project Registration Date',
    'Crediting Period Start Date',
    'Crediting Period End Date'
]

registered_projects.drop(columns=drop_columns_reg, inplace=True)

registered_projects.head()

,ID,Name,Proponent,Project Type,Country/Area
0,4443,Jinan Pingyin Youran Dairy Cattle Manure Manag...,"Jinan Youran Animal Husbandry Co., Ltd.","Livestock, enteric fermentation, and manure ma...",China
1,4423,NEW HOPE AWMS GHG Mitigation Project In Anhui ...,Multiple Proponents,"Livestock, enteric fermentation, and manure ma...",China
2,4412,Xiding AWMS GHG Mitigation Project,"Xiding Technology Group Co., Ltd.","Livestock, enteric fermentation, and manure ma...",China
3,4376,Haishang Biogas Recovery and Utilization Project,Shaoyang County Haishang Ecological Agricultur...,"Livestock, enteric fermentation, and manure ma...",China
4,4349,Yueyang LFG Power Generation Project,"Yueyang Weiteng New Energy Co., Ltd.",Energy industries (renewable/non-renewable sou...,China

In [17]:
registered_projects.to_csv(r'C:\Users\Victor\Documents\Programming\Portfolio\Power BI\DB\registered_projects.csv', index=False, encoding='utf-8')